### ISSUE TITLE
The post share icons are way too big

### ISSUE THREAD

**Issue by xyluz** [governmentClout/WEB#17]
![capture](https://user-images.githubusercontent.com/13081285/50056507-ffd91780-0111-11e9-9abe-fb34fac8f70c.PNG)

**Comment by ogbeniore** [comment]
![lol](https://user-images.githubusercontent.com/15702449/50095724-6b0c1200-0216-11e9-972f-f0e6234654f6.PNG)
This is what i changed it to @xyluz

**Comment by xyluz** [comment]
Can it be smaller please?

**Comment by ogbeniore** [comment]
fixed
