### ISSUE TITLE
After commenting on a post, it doesn't appear

### ISSUE THREAD

**Issue by xyluz** [governmentClout/WEB#20]

**Comment by oluwabukolatina** [comment]
appear where, please?

**Comment by ogbeniore** [comment]
I remember asking kingsley for this alongside the single post view design he made

**Comment by xyluz** [comment]
@oluwabukolatina @ogbeniore Ask him again please

**Comment by ogbeniore** [comment]
Fixed... the response time for the reations API and the comments API seems to be very long..
