### ISSUE TITLE
Sign Up form redundant repetition 

### ISSUE THREAD

**Issue by xyluz** [governmentClout/WEB#45]
![capture](https://user-images.githubusercontent.com/13081285/52090089-a6895280-25b0-11e9-912d-480a73d0cf3d.PNG)
It doesn't look good that we have repetitions of "password" as label and "password" as placeholder etc.

Let's have examples, for example, the email field, use an example as a placeholder. Or something else entirely.

This way, our fields are uniform, just like the date comes with a pre-filled date.

Also, @oluwabukolatina We have an age limit of 12 years. Please do a check on this. I'll also do a check in the API.

**Comment by oluwabukolatina** [comment]
done
